version: '3'
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - env/test.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data